<a href="https://colab.research.google.com/github/PhamTienLoc/Lab_ML/blob/main/Lab_2_21130429_PhamTienLoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab #2
This lab is the first step to get farmilliar with some common Machine Learning libraries, named ***Pandas*** and ***Matlotlib***.

*   **Deadline: 23:59, 18/03/2024**

#0. Mount Drive

In [8]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive

#1. Import libraries

In [6]:
# code
import matplotlib as plt
import numpy as np
import pandas as pd

#2. Load dataset

*   Load dataset (named ***student-dataset.csv***) using ***read_csv*** from pandas
*   Then, display 10 last examples

In [12]:
# code
dataset = pd.read_csv("student-dataset.csv")
dataset.head(10)

,id,name,nationality,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
5,5,Rochelle Johnson,United States of America,F,NaN,21,3.4,3.1,3.7,5.0,2,4.0,4
6,6,Joey Abreu,China,M,NaN,22,3.7,3.9,3.6,2.0,5,5.0,5
7,7,Preston Suarez,Brazil,M,NaN,22,3.8,3.7,3.6,2.0,5,5.0,4
8,8,Lee Dong,Philippines,F,NaN,24,3.9,3.6,3.2,2.0,4,3.0,5
9,9,Maa'iz al-Dia,Turkey,M,NaN,22,2.4,2.8,3.8,3.0,5,5.0,4

#3. Show statistics of the given dataset

In [13]:
# code
dataset.describe()

,id,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
count,307.000000,0.0,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,153.000000,NaN,21.964169,3.369707,3.414332,3.446580,4.396417,3.986971,4.110749,4.188925
std,88.767487,NaN,1.248013,0.538724,0.476839,0.509081,0.996474,0.928749,0.823936,0.842193
min,0.000000,NaN,19.000000,1.500000,2.100000,1.400000,1.000000,1.000000,1.000000,1.000000
25%,76.500000,NaN,21.000000,3.100000,3.100000,3.200000,4.000000,3.500000,4.000000,4.000000
50%,153.000000,NaN,22.000000,3.500000,3.500000,3.600000,5.000000,4.000000,4.000000,4.000000
75%,229.500000,NaN,23.000000,3.800000,3.800000,3.800000,5.000000,5.000000,5.000000,5.000000
max,306.000000,NaN,26.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000

#4. Sort dataset by ***nationality***

In [14]:
# code
dataset.sort_values(by="nationality")

,id,name,nationality,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
146,146,Juhaina al-Bilal,Bangladesh,F,NaN,20,3.9,3.9,3.9,5.0,5,4.0,5
285,285,Viridiana Ballesteros,Brazil,F,NaN,22,2.8,3.5,3.9,4.0,4,5.0,5
271,271,Jasmine Lopez,Brazil,F,NaN,21,3.8,3.8,1.5,4.0,4,3.0,4
4,4,Brooke Cazares,Brazil,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
96,96,Mateo Cisneros,Brazil,M,NaN,23,3.0,3.4,2.9,4.0,4,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,Siena Ingram,United States of America,F,NaN,21,3.8,3.7,3.8,5.0,5,3.0,5
149,149,Vincent Webster,United States of America,M,NaN,23,2.0,3.7,3.4,5.0,4,3.0,5
151,151,Patrick Carnes,United States of America,M,NaN,22,2.4,3.5,3.6,5.0,3,5.0,5
305,305,Eliana Michelsen,United States of America,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
153,153,Jenna Whitney,United States of America,F,NaN,23,3.7,2.9,3.9,5.0,3,4.0,5

#5. Group dataset by ***nationality*** and ***gender***

In [ ]:
# code

#6. Use scatter plot to represent the relationship between ***age*** and ***refletter.rating***
Rememer adding titles, xlabel, ylabel, ... to the plot

In [ ]:
# code

#7. Use scatter plot to represent the relationship between ***age*** and ***sciences.grade***
Rememer adding titles, xlabel, ylabel, ... to the plot

In [ ]:
#code

#8. Use histogram plot to represent the distribution of ***Age***
using bins=5

In [ ]:
#code

#9. Create a data frame that computes the average of ages in each countries?

Hint: Use groupby, select the age column and aggregate using mean.

In [ ]:
#code

#10. Create a dataframe including average of ***english.grade, math.grade, sciences.grade, language.grade, portfolio.rating, coverletter.rating, refletter.rating*** of each country

In [ ]:
#code

#Finally,
Remember renaming the notebook.